/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Exam {
  'title' : string,
  'description' : string,
  'durationMinutes' : bigint,
}
export interface Question {
  'correctAnswer' : bigint,
  'questionText' : string,
  'options' : Array<string>,
}
export interface StudentResult {
  'examTitle' : string,
  'studentName' : string,
  'score' : bigint,
  'totalQuestions' : bigint,
}
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addQuestion' : ActorMethod<
    [string, string, Array<string>, bigint],
    undefined
  >,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createExam' : ActorMethod<[string, string, bigint], undefined>,
  'getAllResults' : ActorMethod<[], Array<StudentResult>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getExamQuestions' : ActorMethod<[string], Array<Question>>,
  'getExams' : ActorMethod<[], Array<Exam>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'instructorLogin' : ActorMethod<[string, string], boolean>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'registerStudent' : ActorMethod<[string, string, string], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'studentLogin' : ActorMethod<[string, string], boolean>,
  'submitExam' : ActorMethod<[string, string, Array<bigint>], bigint>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];