/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const StudentResult = IDL.Record({
  'examTitle' : IDL.Text,
  'studentName' : IDL.Text,
  'score' : IDL.Nat,
  'totalQuestions' : IDL.Nat,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });
export const Question = IDL.Record({
  'correctAnswer' : IDL.Nat,
  'questionText' : IDL.Text,
  'options' : IDL.Vec(IDL.Text),
});
export const Exam = IDL.Record({
  'title' : IDL.Text,
  'description' : IDL.Text,
  'durationMinutes' : IDL.Nat,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addQuestion' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Vec(IDL.Text), IDL.Nat],
      [],
      [],
    ),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createExam' : IDL.Func([IDL.Text, IDL.Text, IDL.Nat], [], []),
  'getAllResults' : IDL.Func([], [IDL.Vec(StudentResult)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getExamQuestions' : IDL.Func([IDL.Text], [IDL.Vec(Question)], ['query']),
  'getExams' : IDL.Func([], [IDL.Vec(Exam)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'instructorLogin' : IDL.Func([IDL.Text, IDL.Text], [IDL.Bool], []),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'registerStudent' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'studentLogin' : IDL.Func([IDL.Text, IDL.Text], [IDL.Bool], []),
  'submitExam' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Vec(IDL.Nat)],
      [IDL.Nat],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const StudentResult = IDL.Record({
    'examTitle' : IDL.Text,
    'studentName' : IDL.Text,
    'score' : IDL.Nat,
    'totalQuestions' : IDL.Nat,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  const Question = IDL.Record({
    'correctAnswer' : IDL.Nat,
    'questionText' : IDL.Text,
    'options' : IDL.Vec(IDL.Text),
  });
  const Exam = IDL.Record({
    'title' : IDL.Text,
    'description' : IDL.Text,
    'durationMinutes' : IDL.Nat,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addQuestion' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Vec(IDL.Text), IDL.Nat],
        [],
        [],
      ),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createExam' : IDL.Func([IDL.Text, IDL.Text, IDL.Nat], [], []),
    'getAllResults' : IDL.Func([], [IDL.Vec(StudentResult)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getExamQuestions' : IDL.Func([IDL.Text], [IDL.Vec(Question)], ['query']),
    'getExams' : IDL.Func([], [IDL.Vec(Exam)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'instructorLogin' : IDL.Func([IDL.Text, IDL.Text], [IDL.Bool], []),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'registerStudent' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'studentLogin' : IDL.Func([IDL.Text, IDL.Text], [IDL.Bool], []),
    'submitExam' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Vec(IDL.Nat)],
        [IDL.Nat],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };